# Generated by Django 4.2.11 on 2024-05-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SteamGames",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("app_id", models.IntegerField()),
                ("game_name", models.CharField(max_length=300)),
            ],
        ),
    ]
